### ISSUE TITLE
Little improvements to the code

### ISSUE THREAD

**Issue by redasalmi** [TadjerouniMohamedAdel/ouedkniss-crawler#1]
- Please format the code,
- Some imports are set as "var" and others as "let", you could simply switch them all to "const",
- Why not add a "dev" or "start" script in the package.json to test the app directly without installing it,
- Why not add "nodemon" as a dev dependency to help on the app development process.

~~~
...
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev: "nodemon commands.js crawl",
    "start": "node commands.js crawl",
  },
...
~~~

**Comment by TadjerouniMohamedAdel** [comment]
@redasalmi I will cover all this point in the next commit thank you except for the nodemon because he has no benefit in scripting case

**Comment by redasalmi** [comment]
Great, and for nodemon you are right, I totally forgot that you are working on a CLI.
